name:                megaparsec-tutorial
version:             0.1.0.0
github:              "carp-sushi/megaparsec-tutorial"
license:             BSD3
author:              "carp-sushi"
maintainer:          "105142707+carp-sushi@users.noreply.github.com"
copyright:           "Copyright 2022-present, the original author(s)"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/carp-sushi/megaparsec-tutorial#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings
- DeriveGeneric

library:
  source-dirs: src
  dependencies:
  - megaparsec >= 7.0.4
  - text
  - parser-combinators

executables:
  megaparsec-tutorial-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsec-tutorial
    - megaparsec >= 7.0.4
    - text

tests:
  megaparsec-tutorial-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsec-tutorial
